controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    akari_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_state_controller:
      type: joint_state_controller/JointStateController

akari_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - pan
      - tilt
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
