controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    akari_controller:
      type: joint_state_controller/JointStateController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_state_controller:
      type: joint_state_controller/JointStateController

akari_controller:
  ros__parameters:
    joints:
      - pan
      - tilt
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
